config/routes.rb
Rails.application.routes.draw do
  mount GoodJob::Engine, at: "/good_job"

  resource :iqdb, controller: "iqdb", only: [] do
    get :index
    post :search
  end
  resources :artists, only: %i[index new create show destroy edit update] do
    member do
      post :enqueue_all_urls
    end
    collection do
      post :enqueue_everything
    end
  end
  resources :artist_urls, only: %i[index show destroy] do
    member do
      post :enqueue
    end
  end
  resources :submission_files, only: %i[index show] do
    member do
      post :update_e6_posts
      put :modify_backlog
      put :modify_hidden
      put :set_last_known_good
    end
    collection do
      get :backlog
      get :hidden
      put :hide_many
      put :unhide_many
      put :backlog_many
      put :unbacklog_many
      put :enqueue_many
      post :update_matching_e6_posts
    end
  end
  resources :log_events, only: %i[index show]
  resources :archive_imports, only: %i[new create]
  resources :stats, only: :index do
    collection do
      get :selenium
    end
  end
  resources :config, controller: "config", only: %i[index show] do
    collection do
      put :modify
    end
  end
  root to: "artists#index"
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :artist_urls, dependent: :destroy
  has_many :submissions, through: :artist_urls
  has_many :submission_files, through: :submissions

  validates :name, uniqueness: { case_sensitive: false }
  validates :name, printable_string: true
  validates :name, length: { in: 1..64 }

  attr_accessor :url_string

  def add_artist_url(url)
    result = Sites.from_gallery_url url

    if !result
      errors.add(:url, "#{url} is not a supported url")
      return
    elsif !result[:valid]
      errors.add(:identifier, "#{result[:identifier]} is not valid for #{result[:site].display_name}")
      return
    end

    artist_url = artist_urls.new(
      site_type: result[:site].site_type,
      url_identifier: result[:identifier],
      created_at_on_site: Time.current,
      about_on_site: "",
    )

    artist_url.save

    if artist_url.errors.any?
      errors.add(:base, "#{url} is not valid: #{artist_url.errors.full_messages.join(',')}")
    end

    artist_url
  end

  def enqueue_all_urls
    artist_urls.each(&:enqueue_scraping)
  end

  def oldest_last_scraped_at
    scraper_urls = artist_urls.select(&:scraper_enabled?)
    return nil if scraper_urls.any? { |artist_url| artist_url.last_scraped_at.nil? }

    scraper_urls.map(&:last_scraped_at).min
  end

  concerning :SearchMethods do
    class_methods do
      def search(params)
        q = all

        q = q.attribute_matches(params[:name], :name)
        q = q.join_attribute_matches(params[:url_identifier], artist_urls: :url_identifier)
        q = q.join_attribute_matches(params[:site_type], artist_urls: :site_type)
        q.order(id: :desc)
      end
    end
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @paginator, @artists = Artist.includes(:artist_urls).search(index_search_params).paginate(params)

    @artist_urls_count = ArtistUrl.select(:artist_id)
      .where(artist: @artists).group(:artist_id).count
    @submissions_count = ArtistSubmission.select(:artist_id).joins(:artist_url)
      .where(artist_url: { artist: @artists }).group(:artist_id).count

    base = SubmissionFile.select(:artist_id).joins(artist_submission: :artist_url)
      .where("artist_url.artist_id": @artists.map(&:id)).group("artist_url.artist_id")
    @submission_files_count = base.count
    @not_uploaded_count = base.search(upload_status: "not_uploaded").reorder("").count
    @larger_size_count = base.search(upload_status: "larger_only_filesize_percentage").reorder("").count
    @larger_dimensions_count = base.search(upload_status: "larger_only_dimensions").reorder("").count
  end

  def show
    @artist = Artist.includes(:artist_urls).find(params[:id])
    @search_params = instance_search_params.merge(artist_id: @artist.id)
    @paginator, @submission_files = SubmissionFile.search(@search_params).with_everything.paginate(params)
  end

  def new
    @artist = Artist.new
  end

  def edit
    @artist = Artist.includes(:artist_urls).find(params[:id])
  end

  def create
    Artist.transaction do
      @artist = Artist.create(artist_params)
      add_new_artist_urls(@artist) if @artist.valid?

      if @artist.errors.any?
        raise ActiveRecord::Rollback
      end
    end
    respond_with(@artist)
  end

  def update
    @artist = Artist.find(params[:id])
    @artist.update(artist_params)
    add_new_artist_urls(@artist)
    respond_with(@artist)
  end

  def destroy
    @artist = Artist.includes(artist_urls: { submissions: :submission_files }).find(params[:id])
    @artist.destroy
    redirect_to artists_path
  end

  def enqueue_all_urls
    @artist = Artist.find(params[:id])
    @artist.enqueue_all_urls
  end

  def enqueue_everything
    Artist.find_each(&:enqueue_all_urls)
  end

  private

  def artist_params
    permitted_params = %i[name url_string]

    params.fetch(:artist, {}).permit(permitted_params)
  end

  def index_search_params
    params.fetch(:search, {}).permit(:name, :url_identifier, :site_type)
  end

  def instance_search_params
    params.fetch(:search, {}).permit(SubmissionFile.search_params)
  end

  def add_new_artist_urls(artist)
    artist.url_string.lines.map(&:strip).compact_blank.each do |url|
      artist.add_artist_url(url)
    end
  end
end

app/helpers/artist_helper.rb
module ArtistHelper
  def active_artist_urls_collection(artist)
    scraping_enabled = artist.artist_urls.select(&:scraper?)
    scraping_enabled.map { |artist_url| ["#{artist_url.unescaped_url_identifier} (#{artist_url.site.display_name})", artist_url.id] }
  end

  def backlog_artist_urls_collection
    artist_url_collection(ArtistUrl.search(in_backlog: true))
  end

  def hidden_artist_urls_collection
    artist_url_collection(ArtistUrl.search(hidden_from_search: true))
  end

  def oldest_last_scraped_at_text(artist)
    return "Never" unless artist.oldest_last_scraped_at

    time_ago artist.oldest_last_scraped_at
  end

  private

  def artist_url_collection(artist_url_collection)
    artist_urls = ArtistUrl.where(id: artist_url_collection.group(:id).count.keys).order(:artist_id)
    artist_urls.map { |artist_url| ["#{artist_url.unescaped_url_identifier} (#{artist_url.site.display_name})", artist_url.id] }
  end
end

app/views/artists/_artist_link.html.erb
<%# locals: (artist_url:) -%>
<div class="artist-link">
  <%= site_icon artist_url do %>
    <%= link_to artist_url.unescaped_url_identifier, artist_path(artist_url.artist, search: { artist_url_id: [artist_url.id] }) %>
    <%= link_to "[U]", enqueue_artist_url_path(artist_url), method: :post, title: "Last scraped: #{last_scraped_at_text(artist_url)}" if artist_url.scraper_enabled? %>
    <% if artist_url.id.in? job_stats.scraping_now %>
      [Scraping now!] <%= scraper_status(artist_url, prefix: "Status") %>
    <% end %>
    <% if job_stats.scraping_queued[artist_url.id] %>
      [Scraping queued] <%= scraper_status(artist_url, prefix: "Status") %>
    <% end %>
    <% if job_stats.submission_download_queued[artist_url.id] %>
      [<%= job_stats.submission_download_queued[artist_url.id] %> pending
        <%= artist_url.site_type == "tumblr" ? "reblogs" : "file downloads" %>]
    <% end %>
    <% if job_stats.e6_iqdb_queued[artist_url.id] %>
      [<%= job_stats.e6_iqdb_queued[artist_url.id] %> pending e6 iqdb calls]
    <% end %>
  <% end %>
</div>

app/views/artists/_secondary_links.html.erb
<%# locals: () -%>
<%= subnav_link_to "Listing", artists_path %>
<%= subnav_link_to "New", new_artist_path %>
<% unless @artist&.id %>
  <%= subnav_link_to "Enqueue Everything", enqueue_everything_artists_path, method: :post, data: { confirm: "Are you sure?" } %>
<% end %>
<% if @artist&.id %>
  |
  <%= subnav_link_to "Enqueue All", enqueue_all_urls_artist_path(@artist), method: :post %>
  <% if instance_variable_defined?(:@search_params)%>
    <%= subnav_link_to "Update IQDB for matching", update_matching_e6_posts_submission_files_path(search: @search_params), method: :post, data: { confirm: "Are you sure?" } %>
  <% end %>
  <%= subnav_link_to "Scraper Logs", log_events_path(search: { loggable_type: "ArtistUrl", loggable_id: @artist.artist_urls.map(&:id).join(",") }) %>
  <%= subnav_link_to "Edit", edit_artist_path(@artist) %>
  <%= subnav_link_to "Delete", artist_path(@artist), method: :delete, data: { confirm: "Are you sure?" } %>
  | <%= render "submission_files/multiselect" %>
<% end %>

app/views/artists/_submission.html.erb
<div class="artist-submission">
  <div class="submission-source">
    Source: <%= submission.artist_url.site.display_name %>
  </div>
  <div class="submission-link">
    Link: <%= link_to submission.artist_url.site.submission_url(submission), submission.artist_url.site.submission_url(submission) %>  
  </div>
  <div class="submission-time">
    Time: <%= submission.created_at_on_site %>
  </div>
  <% if submission.title_on_site.present? %>
    <div class="submission-title">
      Title: <%= submission.title_on_site %>
    </div>
  <% end %>
  <% if submission.description_on_site.present? %>
    <div class="submission-description">
      Description: <%= submission.description_on_site %>
    </div>
  <% end %>
  <div class="submission-container">
    <% submission.submission_files.each do |file| %>
      <%= render "submission_file", submission_file: file %>
    <% end %>
  </div>
</div>

app/views/artists/_submission_file.html.erb
<%# Handle missing attachments %>
<% if submission_file.original.content_type == "image/jpeg" %>
  <%= image_tag url_for(submission_file.sample) %>
<% elsif submission_file.original.content_type == "video/mp4" %>
  <%= video_tag url_for(submission_file.sample) %>
<% else %>
  Unhandled content_type <%= submission_file.original.content_type %>
<% end %>

app/views/artists/edit.html.erb
Current Links:
<%= render "artist_urls/list", artist_urls: ordered_artist_urls(@artist) %>
<%= form_errors(@artist) %>
<%= form_with model: @artist do |f| %>
  <%= f.input :name, as: :string %>
  <%= f.input :url_string, as: :textarea, label: "New Links", rows: 10, cols: 50 %>
  <%= f.submit %>
<% end %>

<% page_title "Edit #{@artist.name}" %>

app/views/artists/index.html.erb
<%= hideable_search(artists_path) do |f| %>
  <%= f.input :name %>
  <%= f.input :url_identifier %>
  <%= f.input :site_type, label: "Site", collection: site_types_collection, include_blank: true %>
<% end %>

<table class="table full-width">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>URLs</th>
      <th>Last scraped</th>
      <th>Submissions</th>
      <th>Files</th>
      <th>Not Uploaded</th>
      <th>Larger Size</th>
      <th>Larger Dimensions</th>
    </tr>
  </thead>
  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= link_to artist.id, artist_path(artist) %></td>
        <td><%= artist.name %></td>
        <td><%= @artist_urls_count[artist.id] || 0 %></td>
        <td><%= oldest_last_scraped_at_text(artist) %></td>
        <td><%= @submissions_count[artist.id] || 0 %></td>
        <td><%= @submission_files_count[artist.id] || 0 %></td>
        <td><%= link_to @not_uploaded_count[artist.id] || 0, artist_path(artist, search: { upload_status: "not_uploaded" }) %></td>
        <td><%= link_to @larger_size_count[artist.id] || 0, artist_path(artist, search: { upload_status: "larger_only_filesize_percentage" }) %></td>
        <td><%= link_to @larger_dimensions_count[artist.id] || 0, artist_path(artist, search: { upload_status: "larger_only_dimensions" }) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% page_title "Artists" %>

app/views/artists/new.html.erb
<%= form_errors(@artist) %>
<%= form_with model: @artist do |f| %>
  <%= f.input :name, as: :string %>
  <%= f.input :url_string, as: :textarea, label: "Links", rows: 10, cols: 50 %>
  <%= f.submit %>
<% end %>

<% page_title "New Artist" %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>

Links:
<%= render "artist_urls/list", artist_urls: ordered_artist_urls(@artist) %>

<%= render "submission_files/list_with_search", path: artist_url(@artist), artist_urls: active_artist_urls_collection(@artist), submission_files: @submission_files %>

<% page_title @artist.name %>