config/routes.rb
Rails.application.routes.draw do
  mount GoodJob::Engine, at: "/good_job"

  resource :iqdb, controller: "iqdb", only: [] do
    get :index
    post :search
  end
  resources :artists, only: %i[index new create show destroy edit update] do
    member do
      post :enqueue_all_urls
    end
    collection do
      post :enqueue_everything
    end
  end
  resources :artist_urls, only: %i[index show destroy] do
    member do
      post :enqueue
    end
  end
  resources :submission_files, only: %i[index show] do
    member do
      post :update_e6_posts
      put :modify_backlog
      put :modify_hidden
      put :set_last_known_good
    end
    collection do
      get :backlog
      get :hidden
      put :hide_many
      put :unhide_many
      put :backlog_many
      put :unbacklog_many
      put :enqueue_many
      post :update_matching_e6_posts
    end
  end
  resources :log_events, only: %i[index show]
  resources :archive_imports, only: %i[new create]
  resources :stats, only: :index do
    collection do
      get :selenium
    end
  end
  resources :config, controller: "config", only: %i[index show] do
    collection do
      put :modify
    end
  end
  root to: "artists#index"
end

app/models/log_event.rb
class LogEvent < ApplicationRecord
  belongs_to :loggable, polymorphic: true

  enum :action, {
    scraper_request: 0,
  }

  PARAMETER_FILTER = ActiveSupport::ParameterFilter.new(Rails.application.config.filter_parameters)

  def self.add!(model, action, payload = {})
    create!(
      loggable_id: model.id,
      loggable_type: model.class.name,
      action: action,
      payload: PARAMETER_FILTER.filter(payload),
    )
  end

  def self.search(params)
    q = all

    q = q.attribute_matches(params[:loggable_id], :loggable_id)
    q = q.attribute_matches(params[:loggable_type], :loggable_type)
    q = q.attribute_matches(params[:action], :action)
    q = q.attribute_matches(params[:payload], :payload)

    q.order(id: :desc)
  end
end

app/controllers/log_events_controller.rb
class LogEventsController < ApplicationController
  def index
    @paginator, @log_events = LogEvent.search(search_params).paginate_and_decorate(params)
  end

  def show
    @log_event = LogEvent.find(params[:id]).decorate
  end

  private

  def search_params
    params.fetch(:search, {}).permit(:loggable_id, :loggable_type, :action, :payload)
  end
end

app/views/log_events/_secondary_links.html.erb
<%# locals: () -%>
<%= subnav_link_to "Listing", log_events_path %>

app/views/log_events/index.html.erb
<%= hideable_search(log_events_path) do |f| %>
  <%= f.input :loggable_type %>
  <%= f.input :loggable_id %>
  <%= f.input :action, collection: LogEvent.actions, include_blank: true %>
  <%= f.input :payload %>
<% end %>

<table class="table full-width">
  <thead>
    <tr>
      <th>Timestamp</th>
      <th>Type</th>
      <th>ID</th>
      <th>Action</th>
      <th>Details</th>
      <th>Preview</th>
    </tr>
  </thead>
  <tbody>
    <% @log_events.each do |log_event| %>
      <tr>
        <td><%= time_ago log_event.created_at %></td>
        <td><%= log_event.loggable_type %></td>
        <td><%= log_event.loggable_id %></td>
        <td><%= log_event.action %></td>
        <td><%= link_to "Details", log_event_path(log_event) %></td>
        <td class="break-all"><%= log_event.preview %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% page_title "Logs" %>

app/views/log_events/show.html.erb
<div class="break-all"><%= @log_event.full_text %></div>

<% page_title "Log - #{@log_event.id}" %>