config/routes.rb
Rails.application.routes.draw do
  mount GoodJob::Engine, at: "/good_job"

  resource :iqdb, controller: "iqdb", only: [] do
    get :index
    post :search
  end
  resources :artists, only: %i[index new create show destroy edit update] do
    member do
      post :enqueue_all_urls
    end
    collection do
      post :enqueue_everything
    end
  end
  resources :artist_urls, only: %i[index show destroy] do
    member do
      post :enqueue
    end
  end
  resources :submission_files, only: %i[index show] do
    member do
      post :update_e6_posts
      put :modify_backlog
      put :modify_hidden
      put :set_last_known_good
    end
    collection do
      get :backlog
      get :hidden
      put :hide_many
      put :unhide_many
      put :backlog_many
      put :unbacklog_many
      put :enqueue_many
      post :update_matching_e6_posts
    end
  end
  resources :log_events, only: %i[index show]
  resources :archive_imports, only: %i[new create]
  resources :stats, only: :index do
    collection do
      get :selenium
    end
  end
  resources :config, controller: "config", only: %i[index show] do
    collection do
      put :modify
    end
  end
  root to: "artists#index"
end

app/models/submission_file.rb
class SubmissionFile < ApplicationRecord
  belongs_to :artist_submission
  has_many :e6_posts, dependent: :destroy
  has_many :relevant_e6_posts, -> { where(similarity_score: Config.similarity_cutoff..) }, inverse_of: :submission_file, dependent: nil, class_name: "E6Post"

  validate :original_present

  after_destroy_commit :remove_from_iqdb
  after_save_commit :update_variants_and_iqdb
  # This adds framework after_commit hooks which must run after
  # the ones above for attachment_changes to work correctly
  has_one_attached :original
  has_one_attached :sample

  scope :with_attached, -> { with_attached_sample.with_attached_original }
  scope :with_everything, -> { with_attached.includes(:relevant_e6_posts, artist_submission: :artist_url) }

  scope :larger_iqdb_filesize_kb_exists, ->(treshold) { select_from_e6_posts_where_exists("size - ? > post_size and not post_is_deleted", treshold) }
  scope :larger_iqdb_filesize_percentage_exists, ->(treshold) { select_from_e6_posts_where_exists("size - (size / 100 * ?) > post_size and not post_is_deleted", treshold) }
  scope :smaller_iqdb_filesize_doesnt_exist, -> { select_from_e6_posts_where_not_exists("size <= post_size") }
  scope :larger_only_filesize_kb, ->(treshold) { larger_iqdb_filesize_kb_exists(treshold).smaller_iqdb_filesize_doesnt_exist.exact_match_doesnt_exist }
  scope :larger_only_filesize_percentage, ->(treshold) { larger_iqdb_filesize_percentage_exists(treshold).smaller_iqdb_filesize_doesnt_exist.exact_match_doesnt_exist }

  scope :larger_iqdb_dimensions_exist, -> { select_from_e6_posts_where_exists("width > post_width and height > post_height and not post_is_deleted") }
  scope :smaller_iqdb_dimensions_dont_exist, -> { select_from_e6_posts_where_not_exists("width <= post_width and height <= post_height") }
  scope :larger_only_dimensions, -> { larger_iqdb_dimensions_exist.smaller_iqdb_dimensions_dont_exist }

  scope :already_uploaded, -> { select_from_e6_posts_where_exists }
  scope :not_uploaded, -> { select_from_e6_posts_where_not_exists }
  scope :exact_match_exists, -> { select_from_e6_posts_where_exists("is_exact_match") }
  scope :exact_match_doesnt_exist, -> { select_from_e6_posts_where_not_exists("is_exact_match") }

  # avoid_posting and conditional_dnp never appear alone
  NON_ARTIST_TAGS = %w[unknown_artist unknown_artist_signature sound_warning epilepsy_warning].freeze

  scope :zero_sources, -> { joins(:relevant_e6_posts).where(relevant_e6_posts: { post_is_deleted: false }).where("jsonb_array_length(post_json->'sources') = 0") }
  scope :zero_artists, -> {
    artists_path = "post_json->'tags'->'artist'"
    artists_count = "jsonb_array_length(#{artists_path})"
    joins(:relevant_e6_posts).where(relevant_e6_posts: { post_is_deleted: false }).where("#{artists_count} = 0 or (#{artists_count} = 1 and #{artists_path}->>0 in (?))", NON_ARTIST_TAGS)
  }

  delegate :artist_url, :artist, to: :artist_submission

  def self.select_from_e6_posts_where_exists(condition = nil, *condition_args)
    where("exists (#{select_from_e6_posts(condition)})", *condition_args)
  end

  def self.select_from_e6_posts_where_not_exists(condition = nil, *condition_args)
    where("not exists (#{select_from_e6_posts(condition)})", *condition_args)
  end

  def self.select_from_e6_posts(condition)
    "select from e6_posts where submission_files.id = e6_posts.submission_file_id and e6_posts.similarity_score >= #{Config.similarity_cutoff} #{"and #{condition}" if condition}"
  end

  def self.blob_for_io(io, filename)
    # Deviantart doesn't have to return only images.
    # No way to find this out through the api response as far as I'm aware.
    # https://www.deviantart.com/fr95/art/779625010/
    mime_type = Marcel::MimeType.for io
    return if mime_type.in? Scraper::Submission::MIME_IGNORE

    ActiveStorage::Blob.create_and_upload!(io: io, filename: filename, content_type: mime_type, identify: false)
  end

  def self.from_attachable(attachable:, artist_submission:, url:, created_at:, file_identifier:)
    submission_file = SubmissionFile.new(
      artist_submission: artist_submission,
      direct_url: url,
      created_at_on_site: created_at,
      file_identifier: file_identifier,
    )
    case attachable
    when Tempfile
      submission_file.attach_original_from_file!(attachable)
    when ActiveStorage::Blob
      submission_file.attach_original_from_blob!(attachable)
    else
      raise ArgumentError, "'#{attachable.class}' is not supported"
    end
  end

  def attach_original_from_file!(file)
    filename = File.basename(Addressable::URI.parse(direct_url).path)
    blob = self.class.blob_for_io(file, filename)
    begin
      attach_original_from_blob!(blob) if blob
    rescue StandardError => e
      blob.purge
      raise e
    end
  end

  def attach_original_from_blob!(blob)
    metadata = ActiveStorage::Analyzer::ImageAnalyzer::Vips.new(blob).metadata
    raise StandardError, "Failed to analyze" if blob.content_type == "application/octet-stream"
    raise StandardError, "'#{blob.content_type}' is not allowed" if blob.content_type.in? Scraper::Submission::MIME_IGNORE

    self.width = metadata[:width]
    self.height = metadata[:height]
    self.content_type = blob.content_type
    self.size = blob.byte_size

    if can_iqdb?
      begin
        Vips::Image.new_from_file(file_path_for(blob), fail: true).stats
      rescue Vips::Error => e
        self.file_error = e.message.strip
      end
    end

    original.attach(blob)
    save!
  end

  def corrupt?
    file_error.present?
  end

  def original_attachment=(new_attachment)
    super
    @original_purged = new_attachment.nil?
  end

  def original_present
    return if new_record? ? original.attached? : @original_purged != true

    errors.add(:original_file, "not attached")
  end

  def sample_generated?
    original.analyzed? && sample&.attached?
  end

  def md5
    base64_decoded = original.checksum.unpack1("m")
    base64_decoded.unpack1("H*")
  end

  def can_iqdb?
    IqdbProxy.can_iqdb?(content_type)
  end

  def update_variants_and_iqdb
    return if attachment_changes["original"].blank?

    SubmissionFileUpdateJob.perform_later(self)
  end

  def update_e6_posts(priority: E6IqdbQueryJob::PRIORITIES[:manual_action])
    e6_posts.destroy_all
    similar = IqdbProxy.query_submission_file(self).pluck(:submission_file)
    similar.each { |s| s.e6_posts.destroy_all }

    E6IqdbQueryJob.set(priority: priority).perform_later(self)
    similar.each do |s|
      # Process matches from other artists after everything else.
      # Chances are that they're just wrong iqdb matches.
      priority_for_similar = s.artist_submission.artist == artist_submission.artist ? priority : priority + 50
      E6IqdbQueryJob.set(priority: priority_for_similar).perform_later(s)
    end
  end

  def update_e6_posts!
    e6_posts.destroy_all

    sample.open do |file|
      # FIXME: Error handling
      json = E6ApiClient.iqdb_query(file)
      break unless json.is_a? Array

      json.each do |entry|
        post_id = entry["post"]["posts"]["id"]
        post_json = E6ApiClient.get_post(post_id)
        post_entry = e6_posts.create(
          post_id: post_json["id"],
          post_width: post_json["file"]["width"],
          post_height: post_json["file"]["height"],
          post_size: post_json["file"]["size"],
          post_is_deleted: post_json["flags"]["deleted"],
          post_json: post_json,
          similarity_score: entry["score"],
          is_exact_match: md5 == post_json["file"]["md5"] || existing_matches(post_json["id"], is_exact_match: true).any?,
        )

        # Check if there are entries which were previously added
        # that are an exact visual match to this newly added exact match
        if post_entry.is_exact_match
          existing_matches(post_json["id"], is_exact_match: false).find_each do |existing_match|
            existing_match.update(is_exact_match: true)
          end
        end
      end
    end
  end

  def existing_matches(post_id, is_exact_match:)
    E6Post.joins(:submission_file)
      .where(post_id: post_id, submission_file: { iqdb_hash: iqdb_hash }, is_exact_match: is_exact_match)
  end

  def remove_from_iqdb
    IqdbProxy.remove_submission self if can_iqdb?
  end

  def generate_variants
    io = VariantGenerator.sample(file_path_for(:original), content_type)
    sample.attach(io: io, filename: "sample")
  end

  def file_path_for(variant_or_blob)
    blob = variant_or_blob.is_a?(Symbol) ? send(variant_or_blob) : variant_or_blob
    blob.service.path_for(blob.key)
  end

  def url_for(variant, **)
    Rails.application.routes.url_helpers.rails_blob_path(send(variant), only_path: true, **)
  end

  concerning :SearchMethods do
    class_methods do
      def search(params)
        q = status_search(params)
        q = q.zero_sources if params[:zero_sources] == "1"
        q = q.zero_artists if params[:zero_artists] == "1"
        q = q.attribute_matches(params[:content_type], :content_type)
        q = q.attribute_nil_check(params[:in_backlog], :added_to_backlog_at)
        q = q.attribute_nil_check(params[:hidden_from_search] || false, :hidden_from_search_at)
        q = q.attribute_nil_check(params[:corrupt], :file_error)
        q = q.join_attribute_matches(params[:title], artist_submission: :title_on_site)
        q = q.join_attribute_matches(params[:description], artist_submission: :description_on_site)
        q = q.join_attribute_matches(params[:artist_url_id], artist_submission: { artist_url: :id })
        q = q.join_attribute_matches(params[:artist_id], artist_submission: { artist_url: { artist: :id } })
        q = q.join_attribute_matches(params[:site_type], artist_submission: { artist_url: :site_type })
        q.order(created_at_on_site: :desc, file_identifier: :desc)
      end

      def status_search(params)
        if params[:upload_status].present?
          case params[:upload_status]
          when "larger_only_filesize_kb"

app/controllers/submission_files_controller.rb
class SubmissionFilesController < ApplicationController
  def index
    @search_params = search_params
    @paginator, @submission_files = SubmissionFile.search(@search_params).with_everything.paginate(params)
  end

  def show
    @submission_file = SubmissionFile.find(params[:id])
    @artist_submission = @submission_file.artist_submission
    @similar = []
    @similar = IqdbProxy.query_submission_file(@submission_file) if @submission_file.can_iqdb? && @submission_file.sample_generated?
  end

  def modify_backlog
    submission_file = SubmissionFile.find(params[:id])
    in_backlog = params[:type] == "add"
    submission_file.update(added_to_backlog_at: in_backlog ? Time.current : nil)
  end

  def modify_hidden
    submission_file = SubmissionFile.find(params[:id])
    hide_from_search = params[:type] == "add"
    submission_file.update(hidden_from_search_at: hide_from_search ? Time.current : nil)
  end

  def set_last_known_good
    submission_file = SubmissionFile.find(params[:id])
    submission_file.artist_url.update(last_scraped_at: submission_file.created_at_on_site - 1.day)
  end

  def update_e6_posts
    submission_file = SubmissionFile.find(params[:id])
    submission_file.update_e6_posts(priority: E6IqdbQueryJob::PRIORITIES[:immediate])
  end

  def update_matching_e6_posts
    UpdateMatchingE6PostsJob.perform_later(search_params)
  end

  def backlog
    @search_params = search_params.merge(in_backlog: true)
    @paginator, @submission_files = SubmissionFile.search(@search_params)
      .with_everything
      .reorder(added_to_backlog_at: :desc)
      .paginate(params)
  end

  def hidden
    @search_params = search_params.merge(hidden_from_search: true)
    @paginator, @submission_files = SubmissionFile.search(@search_params)
      .with_everything
      .reorder(hidden_from_search_at: :desc)
      .paginate(params)
  end

  def hide_many
    SubmissionFile.where(id: params[:ids], hidden_from_search_at: nil).find_each do |submission_file|
      submission_file.update(hidden_from_search_at: Time.current)
    end
  end

  def unhide_many
    SubmissionFile.where(id: params[:ids]).where.not(hidden_from_search_at: nil).find_each do |submission_file|
      submission_file.update(hidden_from_search_at: nil)
    end
  end

  def backlog_many
    SubmissionFile.where(id: params[:ids], added_to_backlog_at: nil).find_each do |submission_file|
      submission_file.update(added_to_backlog_at: Time.current)
    end
  end

  def unbacklog_many
    SubmissionFile.where(id: params[:ids]).where.not(added_to_backlog_at: nil).find_each do |submission_file|
      submission_file.update(added_to_backlog_at: nil)
    end
  end

  def enqueue_many
    SubmissionFile.where(id: params[:ids]).find_each(&:update_e6_posts)
  end

  private

  def search_params
    params.fetch(:search, {}).permit(SubmissionFile.search_params)
  end
end

app/helpers/submission_file_helper.rb
module SubmissionFileHelper
  def display_artist_name?(submission_file)
    s1 = submission_file.artist_url.url_identifier.downcase
    s2 = submission_file.artist.name.downcase
    s1.gsub(/\W+/, "") != s2.gsub(/\W+/, "")
  end

  def submission_file_tag(submission_file)
    dimensions = { width: submission_file.width, height: submission_file.height }
    sample = image_tag(submission_file.url_for(:sample), loading: "lazy", class: "submission-file", **dimensions, data: { corrupt: submission_file.corrupt? })
    sample + original_file_tag(submission_file)
  end

  def original_file_tag(submission_file)
    url = submission_file.url_for(:original)
    dimensions = { width: submission_file.width, height: submission_file.height }
    if submission_file.original.content_type.in? ["video/mp4", "video/webm", "video/quicktime"]
      video_tag(url, controls: false, class: "submission-file-full hidden", **dimensions)
    else
      image_tag(url, loading: "lazy", class: "submission-file-full hidden", **dimensions)
    end
  end
end

app/views/submission_files/_e6_post_stats.html.erb
<%# locals: (submission_file:) -%>
<% submission_file.relevant_e6_posts.sort_by(&:similarity_score).reverse_each do |entry| %>
  <div>
  <%= link_to_external "##{entry.post_id}", "https://e621.net/posts/#{entry.post_id}", title: "Score: #{entry.score}" %>
  <% if entry.post_is_deleted? %>
    <span title="Deleted">!</span>
  <% else %>
    <%= link_to_external "E6D", entry.direct_url, title: "E6 Direct Link" %>
  <% end %>
  <% if entry.is_exact_match? %>
    Exact
  <% else %>
    <span class="size-difference">
      <%= number_to_human_size(entry.post_size - submission_file.size, precision: 2) %>
    </span>
    <span class="dimension-difference" title="<%= "#{entry.post_width}x#{entry.post_height}" %>">
      x<%= (entry.post_width / submission_file.width.to_f).round(1) %>
    </span>
  <% end %>
  </div>
<% end %>

app/views/submission_files/_list_with_search.html.erb
<%# locals: (path:, artist_urls:, submission_files:) -%>
<%= render "submission_files/search", path: path, artist_urls: artist_urls %>

<% submission_files.each do |file| %>
  <%= render "submission_files/sample", submission_file: file %>
<% end %>

app/views/submission_files/_multiselect.html.erb
<%# locals: () -%>
<%= toggleable("multiselect", "Enter select mode", "Leave select mode", visible_on_load: false) do %>
  <li>(<span id="selected-count">0</span>)</li>
  <li><%= fake_link("Hide", id: "hide-selected") %></li>
  <li><%= fake_link("Unhide", id: "unhide-selected") %></li>
  <li><%= fake_link("Backlog", id: "backlock-selected") %></li>
  <li><%= fake_link("Unbacklog", id: "unbacklock-selected") %></li>
  <li><%= fake_link("Enqueue", id: "enqueue-selected") %></li>
  <li><%= fake_link("Select All", id: "select-all") %></li>
<% end %>

app/views/submission_files/_sample.html.erb
<%# locals: (submission_file:, similarity: nil) -%>
<%= tag.div class: "submission-sample", data: { id: submission_file.id } do %>
  <% if submission_file.sample_generated? %>
    <div class="file-container">
      <% if submission_file.sample.content_type.in? %w[image/jpeg image/gif] %>
        <%= submission_file_tag(submission_file) %>
      <% else %>
        Unhandled content_type <%= submission_file.sample.content_type %>
      <% end %>
    </div>
  <% else %>
    Sample not generated
  <% end %>
  <%= render "submission_files/stats", submission_file: submission_file, similarity: similarity %>
<% end %>

app/views/submission_files/_search.html.erb
<%# locals: (path:, artist_urls:) -%>
<%= hideable_search(path) do |f| %>
  <%= f.input :artist_url_id, label: "URLs", collection: artist_urls, multiple: true if artist_urls.any? %>
  <%= f.input :upload_status, label: "Status", collection: [
    ["Larger Only (Filesize kB)", "larger_only_filesize_kb"],
    ["Larger Only (Filesize %)", "larger_only_filesize_percentage"],
    ["Larger Only (Dimensions)", "larger_only_dimensions"],
    ["Already Uploaded", "already_uploaded"],
    ["Exact Match", "exact_match_exists"],
    ["Not Uploaded", "not_uploaded"],
  ], include_blank: true %>
  <%= f.input :larger_only_filesize_treshold, label: "Larger Only Treshold" %>
  <%= f.input :content_type, collection: [
    ["Animation Only", "video/mp4,video/webm,video/quicktime,image/gif"],
    ["Pictures Only", "image/png,image/jpeg,"],
  ], include_blank: true %>
  <%= f.input :site_type, label: "Site", collection: site_types_collection, include_blank: true %>
  <%= f.input :in_backlog, label: "In Backlog?", collection: [
    %w[Yes true],
    %w[No false],
  ], include_blank: true %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :corrupt, as: :checkbox %>
  <%= f.input :zero_sources, as: :checkbox %>
  <%= f.input :zero_artists, as: :checkbox %>
<% end %>

app/views/submission_files/_secondary_links.html.erb
<%# locals: () -%>
<%= subnav_link_to "Backlog", backlog_submission_files_path %>
<%= subnav_link_to "Hidden", hidden_submission_files_path %>
<% if instance_variable_defined?(:@search_params) %>
  <%= subnav_link_to "Update IQDB for matching", update_matching_e6_posts_submission_files_path(search: @search_params), method: :post, data: { confirm: "Are you sure?" } %>
<% end %>
<% if @submission_file&.id %>
  |
  <%= subnav_link_to "All From Artist", artist_path(@submission_file.artist) %>
  <%= subnav_link_to "All From URL", artist_path(@submission_file.artist, search: { artist_url_id: [@submission_file.artist_url.id] }) %>
  <%= subnav_link_to "Update E6 IQDB", update_e6_posts_submission_file_path(@submission_file), method: :post %>
  <% if @submission_file.artist_url.last_scraped_at %>
    |
    <%= subnav_link_to "Last known good", set_last_known_good_submission_file_path(@submission_file), method: :put, data: { confirm: "Fix broken scrapers. Everything after this may be downloaded again if it failed in the past but is now fixed through an update. Will not cause duplicate entries." } %>
  <% end %>
<% end %>
| <%= render "submission_files/multiselect" %>

app/views/submission_files/_stats.html.erb
<%# locals: (submission_file:, similarity:) -%>
<% artist_submission = submission_file.artist_submission %>
<% artist_url = submission_file.artist_url %>
<div class="submission-stats">
  <% if similarity %>
    <div>
      Similarity: <%= similarity.round(2) %>
    </div>
  <% end %>
  <div class="submission-file-stats">
    <%= site_icon artist_url %>
    <%= "#{submission_file.width}x#{submission_file.height}" %>, 
    <%= number_to_human_size submission_file.size %>, 
    <%= Marcel::TYPE_EXTS[submission_file.content_type].first.upcase %>
  </div>
  <div class="submission-time-ago">
    <%= time_ago submission_file.created_at_on_site %>
    <%= link_to "UREV", update_e6_posts_submission_file_path(submission_file), title: "Update e6 post data", method: :post %>
    <% if submission_file.hidden_from_search_at %>
      <%= link_to "UH", modify_hidden_submission_file_path(submission_file, type: "remove"), title: "Add back into search", method: :put %>
    <% else %>
      <%= link_to "H", modify_hidden_submission_file_path(submission_file, type: "add"), title: "Remove from search", method: :put %>
    <% end %>
    <% if submission_file.added_to_backlog_at %>
      <%= link_to "-", modify_backlog_submission_file_path(submission_file, type: "remove"), title: "Remove from backlog", method: :put %>
    <% else %>
      <%= link_to "+", modify_backlog_submission_file_path(submission_file, type: "add"), title: "Add to backlog", method: :put %>
    <% end %>
  </div>
  <div class="submission-links">
    <%= link_to_external "SRC", submission_url(artist_submission), title: "Original Source" %>
    | <%= link_to_external "DLE", submission_file.direct_url, title: "Direct Link External" %>
    | <%= link_to "DLO", submission_file.url_for(:original, disposition: :inline), title: "Direct Link Onsite" %>
    | <%= link_to "REV", submission_file_path(submission_file), title: "Similar Indexed" %>
  </div>
  <div class="e6-links">
    <%= render "submission_files/e6_post_stats", submission_file: submission_file %>
  </div>
</div>

app/views/submission_files/backlog.html.erb
<h1>Backlog</h1>

<%= render "list_with_search", path: backlog_submission_files_path, artist_urls: backlog_artist_urls_collection, submission_files: @submission_files %>

<% page_title "Backlog" %>

app/views/submission_files/hidden.html.erb
<h1>Hidden</h1>

<%= render "list_with_search", path: hidden_submission_files_path, artist_urls: hidden_artist_urls_collection, submission_files: @submission_files %>

<% page_title "Hidden" %>

app/views/submission_files/index.html.erb
<h1>Submission Files</h1>

<div class="search">
  <%= render "submission_files/search", path: submission_files_path, artist_urls: [] %>
</div>

<% @submission_files.each do |file| %>
  <%= render "submission_files/sample", submission_file: file %>
<% end %>

<% page_title "Submission Files" %>

app/views/submission_files/show.html.erb
<h1>
  Submission from <%= @submission_file.artist_url.unescaped_url_identifier %>
  <% if display_artist_name?(@submission_file) %>
    [<%= @submission_file.artist.name %>]
  <% end %>
</h1>

<div class="original">
  <%= render "submission_files/sample", submission_file: @submission_file %>
  <div>
    <% if @artist_submission.title_on_site.present? %>
      <h3 class="title"><%= @artist_submission.title_on_site %></h3>
    <% end %>
    <%= tag.div @artist_submission.description_on_site, class: "description" %>
  </div>
</div>

<% if @submission_file.corrupt? %>
  <div><%= @submission_file.file_error %></div>
<% end %>

<h2>Similar</h2>
<%= render "iqdb/matches", matches: @similar %>

<% page_title "#{@submission_file.artist.name} on #{@submission_file.artist_url.site.display_name}" %>