config/routes.rb
Rails.application.routes.draw do
  mount GoodJob::Engine, at: "/good_job"

  resource :iqdb, controller: "iqdb", only: [] do
    get :index
    post :search
  end
  resources :artists, only: %i[index new create show destroy edit update] do
    member do
      post :enqueue_all_urls
    end
    collection do
      post :enqueue_everything
    end
  end
  resources :artist_urls, only: %i[index show destroy] do
    member do
      post :enqueue
    end
  end
  resources :submission_files, only: %i[index show] do
    member do
      post :update_e6_posts
      put :modify_backlog
      put :modify_hidden
      put :set_last_known_good
    end
    collection do
      get :backlog
      get :hidden
      put :hide_many
      put :unhide_many
      put :backlog_many
      put :unbacklog_many
      put :enqueue_many
      post :update_matching_e6_posts
    end
  end
  resources :log_events, only: %i[index show]
  resources :archive_imports, only: %i[new create]
  resources :stats, only: :index do
    collection do
      get :selenium
    end
  end
  resources :config, controller: "config", only: %i[index show] do
    collection do
      put :modify
    end
  end
  root to: "artists#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_forgery_protection
  before_action :set_start_time
  before_action :normalize_params
  around_action :with_time_zone

  default_form_builder BasicFormBuilder

  EXCEPTION_TYPES = {
    ActionController::BadRequest => 400,
    ActionController::ParameterMissing => 400,
    ActionController::InvalidAuthenticityToken => 403,
    ActionController::UnpermittedParameters => 403,
    ActiveRecord::RecordNotFound => 404,
    ActionController::UnknownFormat => 406,
    PG::ConnectionBad => 503,
  }.freeze
  exception_classes = Rails.env.test? ? EXCEPTION_TYPES.keys : Exception
  rescue_from(*exception_classes, with: :rescue_exception)

  def set_start_time
    @start_time = Time.current.to_f
  end

  def normalize_params
    return unless request.get? || request.head?

    new_params = deep_compact_blank(request.query_parameters)
    redirect_to url_for(params: new_params) if new_params != request.query_parameters
  end

  def with_time_zone(&)
    Time.use_zone(Config.time_zone, &)
  end

  def rescue_exception(exception)
    @exception = exception
    @exception = @exception.cause if @exception.is_a?(ActionView::Template::Error)

    @params = {
      params: request.filtered_parameters.except(:authenticity_token),
      referrer: request.referer,
      user_agent: request.user_agent,
    }
    status = EXCEPTION_TYPES[exception.class] || 500
    error_template = "application/error"
    error_template = "application/#{status}" if lookup_context.template_exists?(status, "application")

    render error_template, formats: [:html], status: status
  end

  def respond_with(model)
    if model.errors.any?
      # Always render new/edit, there are no specific templates for create/update
      render({ "create" => "new", "update" => "edit" }.fetch(action_name, action_name), status: :unprocessable_content)
    else
      redirect_to(url_for(model))
    end
  end

  private

  def deep_compact_blank(hash)
    hash.transform_values do |v|
      if v.is_a?(Array)
        v.compact_blank
      elsif v.is_a?(Hash)
        deep_compact_blank v
      else
        v
      end
    end.compact_blank
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_ago(value)
    return "" if value.nil?

    tag.span value.to_fs(:long), datetime: value.to_fs(:iso8601), class: "time-ago"
  end

  def selenium_path
    "#{request.scheme}://#{request.host}:#{DockerEnv.exposed_vnc_port}?autoconnect=1"
  end

  # Properly support the method keyword argument
  def link_to(name = nil, options = nil, html_options = nil, &)
    if html_options&.dig(:method)
      button_to(name, options, html_options, &)
    else
      super
    end
  end

  def link_to_external(text, url, **)
    link_to text, url, **, rel: "nofollow noopener noreferrer"
  end

  def link_to_current_with_page(text, paginator, page)
    if paginator.current_page == page || page < 1 || page > paginator.last_page
      tag.a(text, "aria-disabled": true)
    else
      link_to(text, request.query_parameters.merge(page: page))
    end
  end

  def fake_link(text, **)
    tag.a(text, href: "#", **, onclick: "return false;")
  end

  def page_title(title)
    content_for(:page_title) { title }
  end

  def toggleable(id, show_text, hide_text, visible_on_load:, &block)
    tag.span(class: "toggleable-container", id: id, data: { content_visible: visible_on_load }) do
      show = fake_link(show_text, class: "link-show")
      hide = fake_link(hide_text, class: "link-hide")
      toggleable_content = block ? capture(&block) : ""
      show.concat(hide).concat(tag.span(toggleable_content, class: "toggleable-content"))
    end
  end

  def hideable_search(path, &)
    search = toggleable("search", "Show Search Options", "Hide Search Options", visible_on_load: params[:search].present?) do
      form_with(scope: :search, method: :get, url: path, builder: HideableSearchFormBuilder, search_params: params[:search] || {}) do |f|
        capture { yield(f) } + f.submit("Search")
      end
    end
    tag.div(search)
  end

  def form_errors(model)
    return if model.errors.none?

    tag.div(id: "form-error") do
      model.errors.full_messages.join(", ")
    end
  end

  def job_stats
    @job_stats ||= JobStats.new
  end
end

app/views/application/404.html.erb
<p>Not found.</p>

<% page_title "Not Found" %>

app/views/application/_deprecations.html.erb
<%# locals: () -%>

<% unless DockerEnv.specifies_postgres_version? %>
  <div>
    Please add <code>POSTGRES_IMAGE_VERSION=18</code> to your <code>.env</code> file to remove this warning.
    <br>Alternatively, set <code>POSTGRES_AUTOMATIC_VERSION=1</code> to do unattended version updates, which will
    require you to do ~yearly database maintenance when they happen.
  </div>
<% end %>

app/views/application/_footer.html.erb
<%# locals: () -%>
FoxTrove
– Rendered in <%= number_with_precision(Time.current.to_f - @start_time, precision: 3) %> seconds
<% if GitHelper.enabled? %>
  – <%= link_to "Github", GitHelper.url %>
  (<%= link_to "#{GitHelper.last_commit_hash} from #{Time.zone.at(GitHelper.last_commit_timestamp).strftime('%Y-%m-%d')}", "#{GitHelper.url}/tree/#{GitHelper.last_commit_hash}" %>)
<% end %>

app/views/application/_navbar.html.erb
<%# locals: () -%>
<nav id="header-nav">
  <%= link_to "", root_path, class: "logo" %>
  <menu class="primary-navbar">
    <%= nav_link_to "Search", iqdb_path %>
    <%= nav_link_to "Artists", artists_path %>
    <%= nav_link_to "Artist URLs", artist_urls_path %>
    <%= nav_link_to "Submission Files", submission_files_path %>
    <%= nav_link_to "Archive Importer", new_archive_import_path %>
    <%= nav_link_to "Stats", stats_path %>
    <%= nav_link_to "Config", config_index_path %>
    <%= nav_link_to "Selenium", selenium_path %>
    <%= nav_link_to "GoodJob", good_job_path %>
  </menu>
  <menu class="secondary-navbar <%= "empty" unless secondary_links_exist? %>">
    <% if secondary_links_exist? %>
        <%= render "#{controller_name}/secondary_links" %>
    <% else %>
      <%= subnav_link_to "Height Placeholder", "" %>
    <% end %>
  </menu>
</nav>

app/views/application/_outdated.html.erb
<%# locals: () -%>

<h3>Your current Docker image is outdated, it is recommended to perform a rebuild:</h3>
<ol style="margin-top: 0">
  <li><code>bin/launch docker down</code></li>
  <li><code>bin/launch docker build</code></li>
  <li><code>bin/launch docker up</code></li>
</ol>
<p>
  Old: <code><%= DockerEnv.master_commit %></code>
  New: <code><%= GitHelper.last_commit_hash %></code><br>
</p>

app/views/application/_paginator.html.erb
<%# locals: (paginator:) -%>

<nav class="paginator">
  <%= link_to_current_with_page "‹ Prev", paginator, paginator.current_page - 1 %>
  <% paginator.pages.each do |page| %>
    <% if page == :gap  %>
      <%= tag.a("…", "aria-disabled": true, "class": "gap") %>
    <% else %>
      <%= link_to_current_with_page page, paginator, page %>
    <% end %>
  <% end %>
  <%= link_to_current_with_page "Next ›", paginator, paginator.current_page + 1 %>
</nav>

app/views/application/error.html.erb
<h1><%= @exception.class.to_s %> exception raised</h1>

<pre><%= @exception.message.dup.force_encoding("utf-8") %></pre>

<h2>Request</h2>
<div class="error-params">
  <pre><%= JSON.pretty_generate(@params) %></pre>
</div>

<h2>Stacktrace</h2>
<div class="error-backtrace">
  <% Rails.backtrace_cleaner.clean(@exception.backtrace).each do |b| %>
    <div class="error-backtrace-line"><%= b %></div>
  <% end %>
</div>

<h2>Framework Stacktrace</h2>
<div class="error-backtrace">
  <% @exception.backtrace.each do |b| %>
    <div class="error-backtrace-line"><%= b %></div>
  <% end %>
</div>

<% page_title "Something went wrong" %>